### ISSUE TITLE
Menu Background Is Gone

### ISSUE THREAD

**Issue by Gogo1951** [cdmichaelb/Outfitter#100]
![image](https://user-images.githubusercontent.com/55365231/168202897-95b7ea38-9bc9-41d0-9054-f9b6f7724e56.png)

**Comment by cdmichaelb** [comment]
Is this TBCC?

**Comment by Gogo1951** [comment]
Yeah TBCC.

**Comment by Gogo1951** [comment]
No longer an issue.
