### ISSUE TITLE
Repository is incompatible with WoWUp

### ISSUE THREAD

**Issue by KevinTyrrell** [cdmichaelb/Outfitter#101]
Installing Outfitter for TBC using WoWUp by inputting the URL of this repository yields the following error:

![image](https://user-images.githubusercontent.com/12791400/169898926-616f97a6-742f-4d0e-8009-a7f3865089d7.png)

The URL I used to attempt to install outfitter was the following: `https://github.com/cdmichaelb/Outfitter`

Given the popularity of WoWUp and the lack of Curseforge as an option, it is highly recommended you make this repository compatible with WoWUp in order to allow ease-of-use when installing.

**Comment by cdmichaelb** [comment]
I've been out of the loop for a while. I talked with wowup briefly about a year ago. I'll see about adding a github action that meets their requirements. If I do that, it should automatically be on wowup.

**Comment by Gogo1951** [comment]
Hey @KevinTyrrell ,

I'm not sure how serious anyone should take WoWUp given they don't have any way to pay devs. A lot of devs don't care about funding, but a lot do too... it's going to likely be the case that about 1/3 of all add-ons just don't work with WoWUp. 

I really hate Curseforge for how they are playing this out, but they are essentially the only place to get all the add-ons at this point. Asking devs to do extra work to cobble together some duct-tape solution... dunno, I don't think there's a ton of value in WoWUp.

I'm [not a shill for Curseforge](https://github.com/ajour/ajour/issues/746#issuecomment-969177618), [I promise](https://github.com/Gogo1951/GogoWatch/commit/686aa1c68493654616a69c374aa04d1dadf3258b#comments). I just don't know that there's any value in trying to support WoWUp. Seems dead on arrival to me.

**Comment by KevinTyrrell** [comment]
@Gogo1951 While I'd love to debate on each point, it's out of the scope of this issue. The reality is that supporting WoWUp simply involves changing the naming scheme of the zip release files. Choosing to not support WoWUp only harms the addon itself (and its dev) by locking out a section of the userbase who do not use Curseforge.

@cdmichaelb Consult the guide posted by WoWUp which may correct the issue: https://wowup.io/guide/wowup/curseforge-migration

**Comment by Cephel** [comment]
@cdmichaelb The only thing needed is to postfix the zip file for the github release with `-bcc`, for example `Outfitter-2.0.64-bcc.zip`, there are other postfixes available too.

**Comment by cdmichaelb** [comment]
Ok, I have a solution thanks to @zakrn from wowup, I will implement it and try pushing a release today.

**Comment by Cephel** [comment]
> today

![clueless](https://user-images.githubusercontent.com/6716857/176995901-7fc9e171-61ff-46ff-997f-134de0539c1d.png) < Lacks critical information

**Comment by ForsakenNGS** [comment]
Any update on this?

**Comment by Gogo1951** [comment]
@ForsakenNGS should work now. Cheers!
