### ISSUE TITLE
Extreme slowness when multiple items have the same name

### ISSUE THREAD

**Issue by OverkillSD** [cdmichaelb/Outfitter#102]
I'm often swapping between items of the same name for higher EHP or threat depending on the boss/instance, especially tier pieces. I have found that when I have both my EHP and my threat version of an item in my bags, Outfitter will freeze my game for several seconds while it tries (usually successfully) to figure out which version I want equipped. Not sure if this is expected, but if there's any way to improve this it would be tremendously helpful.

I can isolate the problem by placing all duplicate-named items used in sets and putting them in the bank - no major slowness when equipping item sets.
I can reproduce the issue by removing all duplicate-named items used in sets from the bank and attempting to equip any set that uses them, especially when the pieces used by the set are the ones in my bags and not already equipped.

**Comment by Gogo1951** [comment]
@OverkillSD I haven't noticed this. Had a warrior with 2x Heartless.

If this is still an issue, please re-open ticket. Thanks!
