### ISSUE TITLE
JC Exclusive Gems prevent swapping sets

### ISSUE THREAD

**Issue by boktai1000** [cdmichaelb/Outfitter#104]
I've had some difficulty recently after picking up Jewelcrafting and attempting to swap some items that have my JC specific gems in them, and I feel like this is possibly going to be a bigger problem in Wrath with how good JC is going to be and the profession exclusive benefits.

In my case, I was coming from my PVE set that had my JC exclusive gem in my legs swapping an entire set to my PVP set which had the JC exclusive gem in my helm.

I'm assuming the order that Outfitter tries to change might be slot order, starting with the helmet - which would have the JC exclusive gem, and fails to swap the item in, even though later in the list it does swap my legs which fixes the JC exclusive gem and would then make the helm able to be swapped.

It's a bit of a niche issue right now, but as mentioned - I think it's about to become a bigger problem with Wrath.

**Comment by Gogo1951** [comment]
Hey @boktai1000 I get that this is a bug... just I think it's a bit of work to fix it. I have a JC and I hit this issue. Trying to figure out a good way to do this. Basically treating any item with a JC gem in it as a unique item... taking the highest value item and ignoring the other... Anyway TBD. Cheers!

**Comment by Gogo1951** [comment]
Yeah OMG is this ever annoying. Now that I have my JC up... this will be a higher priority. =P

![image](https://user-images.githubusercontent.com/55365231/205402623-229e2675-44d8-460b-a04c-2eb0a0c492fb.png)

![image](https://user-images.githubusercontent.com/55365231/205402643-166ace9e-db50-47aa-9a26-999655437469.png)

**Comment by Gogo1951** [comment]
Has to check for trinkets...

Has to check for gems... 

Has to be aware the gems can be in the trinkets...

Oof. That's a lot of work.

We'll need "groups" of all "unique-equipped" conflicts.

**Comment by Gogo1951** [comment]
Oh, it doesn't need to check trinkets, just gems. Got it. Little easier. =P

**Comment by Ghostjs123** [comment]
Hey @Gogo1951, friendly poke to check my PR that addresses this https://github.com/cdmichaelb/Outfitter/pull/123.

**Comment by Gogo1951** [comment]
Hey @Ghostjs123 I am sorry, I don't think I get notified when someone creates a PR, but it's on my list of things to look at now. Didn't mean to delay this. I'll do a review and get it merged. Thanks!

**Comment by Gogo1951** [comment]
This was fixed!
