### ISSUE TITLE
Outfitter not working on just 1 char

### ISSUE THREAD

**Issue by Varidur** [cdmichaelb/Outfitter#108]
Hi, i got this problem today, about Outfitter's minimap icon not movin when i try to drag it to a new position and not changing outfits even if i create new different ones. Gear slots would show the question mark on the top right but gear won't change at all.

On every other char is working normally.
How can i fix this?

thanks

**Comment by Gogo1951** [comment]
@Varidur Really helps to have more details mate. If you had a bug with a non-Warrior please re-open the ticket.
