### ISSUE TITLE
Outfitter set bar not functioning at all

### ISSUE THREAD

**Issue by spazzledazzle** [cdmichaelb/Outfitter#109]
Not entirely sure why but after the latest update the Outfitter set bar no longer works, on one character it has completely vanished and on all the others the buttons no longer function to change sets.

**Comment by Gogo1951** [comment]
@spazzledazzle Really helps to have more details mate. Warrior?

**Comment by Gogo1951** [comment]
Really helps to have more details mate. If you had a bug with a non-Warrior please re-open the ticket.
