### ISSUE TITLE
Outfitter not working on Warriors

### ISSUE THREAD

**Issue by Stuff000** [cdmichaelb/Outfitter#112]
I can't change gear or get the outfitter bar to show up on my warrior and ONLY my warrior. Please how can I fix this? Tried removing WTF, every other addon except outfitter, reinstalled outfitter but nothing.

**Comment by mcnsparkle** [comment]
Had the same issue since the update three days ago, everything works on all characters but not my warrior.

**Comment by Elesario** [comment]
getting same issue, when I log into warrior get the following error:

Date: 2022-09-25 15:24:24
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Outfitter\Outfitter.lua line 1897:
   attempt to call global 'GetSpecialization' (a nil value)
Debug:
   [string "=[C]"]: GetSpecialization()
   [string "@Outfitter\Outfitter.lua"]:1897: TalentsChanged()
   [string "@Outfitter\Outfitter.lua"]:4924: Function()
   [string "@Outfitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:242: OnUpdate2()
   [string "@Outfitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:178: OnUpdate()
   [string "@Outfitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:20:
      ...fitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua:20
Locals:

AddOns:
  Swatter, v3.4.6817 (SwimmingSeadragon)
  Altoholic, v2.5.008
  AtlasLootClassic, vv3.0.2
  AtlasLootClassicData, vv3.0.2
  AtlasLootClassicDungeonsAndRaids, vv3.0.2
  AucAdvanced, v3.4.6825 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6805 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
  AucStatSimple, v3.4.6807 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  ButtonForge, v1.0.6-classic-Wrath
  CharacterStatsTBC, v1.2.4
  Chinchilla, vv2.13.0
  DataStore, v2022.06.05
  DataStoreAgenda, v2.5.008
  DataStoreAuctions, v2.5.008
  DataStoreCharacters, v2022.06.05
  DataStoreContainers, v2.5.008
  DataStoreCrafts, v2.5.008
  DataStoreInventory, v2.5.008
  DataStoreMails, v2022.06.05
  DataStoreQuests, v2.5.008
  DataStoreReputations, v2.5.008
  DataStoreSpells, v2022.06.05
  DataStoreTalents, v2.5.008
  DBMCore, v10690e0
  DBMStatusBarTimers, v10690e0
  DBMVPVEM, v1b93adf
  Decursive, v2.7.8.9
  EasyMail, v4.4.9
  Enchantrix, v3.4.6821 (SwimmingSeadragon)
  EZJunk, v1.0.2
  GatherMate2, v1.46.3-classic
  GuildRosterManager, v1.92991
  HealBot, v3.4.0.0.b8
  HealBotData, v2.5.4.20
  HealBotOptions, v3.4.0.0
  HealBotTips, v3.4.0.0
  Informant, v3.4.6814 (SwimmingSeadragon)
  LFGBulletinBoard, v2.64
  Mapster, v1.9.8
  OmniCC, v9.2.1
  Outfitter, v3.0.0
  Questie, v7.1.3
  Recount, vv3.4.0a
  SlideBar, v3.4.6815 (SwimmingSeadragon)
  Stubby, v3.4.6816 (SwimmingSeadragon)
  TellMeWhen, v9.2.5
  ThreatClassic2, v2.45
  TidyPlatesThreatPlates, v10.5.2
  TomTom, vv3.1.4
  ZPerl, v6.3.4
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=7ee)

**Comment by Gogo1951** [comment]
Thanks! Looking into this.

**Comment by Gogo1951** [comment]
@Elesario thanks for all the details. Very useful. Where is your GTFO?

https://www.curseforge.com/wow/addons/gtfo

And how do you play without Weak Auras?! (=

**Comment by Gogo1951** [comment]
Fixed in latest release!

**Comment by Elesario** [comment]
Thanks, tested it out and working fine now. Great work.

I didn't know about GTFO, but kind of learnt not to stand in fire many years ago 😃, might try it.
As for Weakauras, I've been using and got used to TellMeWhen, so never bothered learning a new addon to do the same thing.
