### ISSUE TITLE
Outfitter not working on some characters

### ISSUE THREAD

**Issue by Allthecats** [cdmichaelb/Outfitter#113]
Specifically my warrior and shaman. On those toons, the bar has vanished despite the option being selected. If I use the gearing window adjacent to the character window to select a gear loadout, it doesn't change the gear, but rather just keeps my old setup with question marks for each item. It's not a question of whether the toon in question has their own set of tabs (warrior stances and shaman totems) above their hot bars, as it works fine for my druid. This error did not exist in any form or fashion prior to the most recent update. I've tried disabling, reloading, everything on my end, with no luck.

**Comment by Gogo1951** [comment]
Can you send the bug you're seeing with Shamen? I have tested Warriors.

**Comment by Gogo1951** [comment]
@Varidur Really helps to have more details mate. If you had a bug with a non-Warrior please re-open the ticket.

**Comment by Gogo1951** [comment]
@Allthecats Really helps to have more details mate. If you had a bug with a non-Warrior please re-open the ticket.
