### ISSUE TITLE
Change Icon: Your Spellbook

### ISSUE THREAD

**Issue by Elesario** [cdmichaelb/Outfitter#114]
I've noticed that if I try to use the "Your Spellbook" option on the "Change Icon" menu option of an outfit then I get an error and no icons other than default show up. Bug report is:

Date: 2022-10-01 16:26:24
ID: 1
Error occured in: AddOn: Questie
Count: 8
Message: Note: AddOn Questie attempted to call a protected function (<unnamed>:SetWidth()) during combat lockdown.
Debug:
   [string "=[C]"]: SetWidth()
   [string "@Questie\Modules\Tracker\LinePool.lua"]:55: SetText()
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:813: Update()
   [string "@Questie\Modules\Quest\QuestieQuest.lua"]:374: val()
   [string "@Questie\Modules\TaskQueue.lua"]:8:
      Questie\Modules\TaskQueue.lua:6
Locals:
None
AddOns:
  Swatter, v3.4.6817 (SwimmingSeadragon)
  Altoholic, v2.5.008
  AtlasLootClassic, vv3.0.4
  AtlasLootClassicData, vv3.0.4
  AtlasLootClassicDungeonsAndRaids, vv3.0.4
  AucAdvanced, v3.4.6825 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
  AucScanData, v3.4.6804 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6805 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
  AucStatSimple, v3.4.6807 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  ButtonForge, v1.0.6-classic-Wrath
  CharacterStatsTBC, v1.2.4
  Chinchilla, vv2.13.0
  DataStore, v2022.06.05
  DataStoreAgenda, v2.5.008
  DataStoreAuctions, v2.5.008
  DataStoreCharacters, v2022.06.05
  DataStoreContainers, v2.5.008
  DataStoreCrafts, v2.5.008
  DataStoreInventory, v2.5.008
  DataStoreMails, v2022.06.05
  DataStoreQuests, v2.5.008
  DataStoreReputations, v2.5.008
  DataStoreSpells, v2022.06.05
  DataStoreTalents, v2.5.008
  DBMCore, vbc857d6
  DBMPartyWotLK, v3.4.14
  DBMStatusBarTimers, vbc857d6
  DBMVPVEM, v1b93adf
  Decursive, v2.7.8.9
  EasyMail, v4.4.9
  Enchantrix, v3.4.6821 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6813 (SwimmingSeadragon)
  EZJunk, v1.0.2
  GatherMate2, v1.46.3-classic
  GuildRosterManager, v1.92991
  HealBot, v3.4.0.0.b8
  HealBotData, v2.5.4.20
  HealBotOptions, v3.4.0.0
  HealBotTips, v3.4.0.0
  Informant, v3.4.6814 (SwimmingSeadragon)
  LFGBulletinBoard, v3.05
  Mapster, v1.9.8
  OmniCC, v9.2.1
  Outfitter, v3.0.0
  PallyPower, vv1.5.0-classic
  Questie, v7.2.4
  Recount, vv3.4.0a
  SlideBar, v3.4.6815 (SwimmingSeadragon)
  Stubby, v3.4.6816 (SwimmingSeadragon)
  TellMeWhen, v9.2.5
  ThreatClassic2, v2.45
  TidyPlatesThreatPlates, v10.5.3
  TomTom, vv3.1.4
  ZPerl, v6.3.4
  ZPerlArcaneBar, v
  ZPerlCustomHighlight, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=89e)

**Comment by Gogo1951** [comment]
Hey @Elesario ,

This is a bug for Questie. (=

**Comment by Gogo1951** [comment]
https://github.com/Questie/Questie/issues/4551

**Comment by Elesario** [comment]
Sorry, must have posted a debug from a different track, here's the correct one:

Date: 2022-11-27 16:55:58
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Outfitter\OutfitterBar.lua line 1227:
   table index is nil
Debug:
   [string "=[C]"]: ?
   [string "@Outfitter\OutfitterBar.lua"]:1227: Activate()
   [string "@Outfitter\OutfitterBar.lua"]:983: SetIconFilter()
   [string "@Outfitter\OutfitterBar.lua"]:967: SetIconSetID()
   [string "@Outfitter\OutfitterBar.lua"]:1059:
      Outfitter\OutfitterBar.lua:1058
   [string "@Outfitter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua"]:1326: ?()
   [string "@Outfitter\Libraries/LibDropdown-1.0.lua"]:705:
      ...rface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:694
   [string "@Outfitter\Libraries/LibDropdown-1.0.lua"]:865: OnClick()
   [string "@Outfitter\Libraries/LibDropdown-1.0.lua"]:383:
      ...rface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:381
Locals:

AddOns:
  Swatter, v3.4.6837 (SwimmingSeadragon)
  Altoholic, v3.4.001
  AtlasLootClassic, vv3.0.7
  AtlasLootClassicData, vv3.0.7
  AtlasLootClassicDungeonsAndRaids, vv3.0.7
  AucAdvanced, v3.4.6844 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6805 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
  AucStatSimple, v3.4.6807 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  ButtonForge, v1.0.13-classic-Wrath
  CharacterStatsTBC, v1.2.4
  Chinchilla, v290d5e5
  DataStore, v2022.10.25
  DataStoreAchievements, v2022.10.25
  DataStoreAgenda, v3.4.001
  DataStoreAuctions, v3.4.001
  DataStoreCharacters, v2022.10.25
  DataStoreContainers, v3.4.001
  DataStoreCrafts, v3.4.001
  DataStoreInventory, v3.4.001
  DataStoreMails, v2022.10.25
  DataStoreQuests, v3.4.001
  DataStoreReputations, v3.4.001
  DataStoreSpells, v2022.10.25
  DataStoreTalents, v3.4.001
  DBMCore, v5b00279
  DBMStatusBarTimers, v5b00279
  DBMVPVEM, v0dab85c
  Decursive, v2.7.8.11
  EasyMail, v4.5.1
  Enchantrix, v3.4.6849 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6813 (SwimmingSeadragon)
  EZJunk, v1.0.2
  GatherMate2, v1.46.3-classic
  GuildRosterManager, v1.948
  HealBot, v3.4.0.0.b8
  HealBotData, v2.5.4.20
  HealBotOptions, v3.4.0.0
  HealBotTips, v3.4.0.0
  Informant, v3.4.6850 (SwimmingSeadragon)
  LFGBulletinBoard, v3.08
  Mapster, v1.10.4
  OmniCC, v10.0.1
  Outfitter, v3.0.0
  Questie, v7.4.5
  Recount, vv3.4.0b
  SlideBar, v3.4.6851 (SwimmingSeadragon)
  Stubby, v3.4.6816 (SwimmingSeadragon)
  TellMeWhen, v10.0.4
  ThreatClassic2, v2.45
  TidyPlatesThreatPlates, v11.1.2
  TomTom, v3.3.5-release
  ZPerl, v7.0.2
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=84f)
