### ISSUE TITLE
FPS Issues

### ISSUE THREAD

**Issue by MaleMale4k** [cdmichaelb/Outfitter#120]
Hey Guys,
When i Switch gear form one Set to another - for like 1-2 Seconds FPS Dropps for like 40 FPS. Ideas?

**Comment by MaleMale4k** [comment]
i saw - https://github.com/cdmichaelb/Outfitter/issues/23
doenst work for me

**Comment by Gogo1951** [comment]
Hey @MaleMale4k ,

Look, likely some issue with some other add-ons. Unless you're willing to figure out which, it's sort of time sink. Better if you come here and say, "I found a conflict with XYZ..." Turn all your add-ons off and see if you still have this problem. I don't have this problem, I change gear all the time across a bunch of toons.
