### ISSUE TITLE
Transparent Windows of Menu

### ISSUE THREAD

**Issue by MaleMale4k** [cdmichaelb/Outfitter#121]
Hi,
im having Transparent Windows of Menus - Normally i switched to an older Version of Outfitter, but it seems like they got removed. help :) ?

**Comment by MaleMale4k** [comment]
![2022-10-27 11_08_17-World of Warcraft](https://user-images.githubusercontent.com/116797932/198242976-c4795bd9-cc8e-48e4-8aa7-4f16dab179d1.png)

**Comment by MaleMale4k** [comment]
im Using 3.0.1

**Comment by Gogo1951** [comment]
Hey @MaleMale4k ,

It's likely some other add-on you have running that's mucking with the background. I don't know which one. I've seen this issue, but only in conjunction with other add-ons.
