### ISSUE TITLE
Cooking Automation not working

### ISSUE THREAD

**Issue by Blackspectre1** [cdmichaelb/Outfitter#125]
Hi there,

I'm trying to use my Chef's Hat but the automation: "Equip while cooking window is open" isn't functioning. All my other automations work but this one doesn't. Kind of weird so I don't think it's my WTF folder or anything like that.

Regards,

Black

**Comment by Kpral** [comment]
Figured this one out.  Go into the script source and change the following:

if event == "TRADE_SKILL_SHOW" then
    local skillLineID, _, _, _, _, skillLineID2 = C_TradeSkillUI.GetTradeSkillLine()
    if skillLineID == 185 or skillLineID2 == 185 then
        equip = true
    end
elseif event == "TRADE_SKILL_CLOSE" then
    if didEquip then
        equip = false
    end
elseif event == "TRADE_SKILL_UPDATE" then
    local skillLineID, _, _, _, _, skillLineID2 = C_TradeSkillUI.GetTradeSkillLine()
    if skillLineID == 185 or skillLineID2 == 185 then
        equip = true
    elseif didEquip then
        equip = false
    end
end

to:

if event == "TRADE_SKILL_SHOW" then
    local skillLineID, _, _, _ = GetTradeSkillLine()
    if skillLineID == "Cooking" then
        equip = true
    end
elseif event == "TRADE_SKILL_CLOSE" then
    if didEquip then
        equip = false
    end
elseif event == "TRADE_SKILL_UPDATE" then
    local skillLineID, _, _, _ = GetTradeSkillLine()
    if skillLineID == "Cooking" then
        equip = true
    elseif didEquip then
        equip = false
    end
end

**Comment by Blackspectre1** [comment]
You are a genius, that worked perfectly.

Cheers,

Joel
________________________________

**Comment by Gogo1951** [comment]
Hey @Kpral , submit a PR for this! (=

**Comment by Gogo1951** [comment]
I pushed this into the Alpha Channel. I can't test it myself, since I don't have the hat, but I'll leave it on Alpha for a few days and if we don't get any complaints I'll merge it into Production. Cheers!
