### ISSUE TITLE
Lua Error on Load

### ISSUE THREAD

**Issue by Gogo1951** [cdmichaelb/Outfitter#128]
10x Outfitter/OutfitterUITools.lua:322: attempt to call method 'SetGradientAlpha' (a nil value)
[string "@Outfitter/OutfitterUITools.lua"]:322: in function `Construct'
[string "@Outfitter/Outfitter.lua"]:4732: in function `Function'
[string "@Outfitter/Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:242: in function `OnUpdate2'
[string "@Outfitter/Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:178: in function `OnUpdate'
[string "@Outfitter/Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:20: in function <...fitter/Libraries/MC2SchedulerLib/MC2SchedulerLib.lua:20>

Locals:
self = OutfitterFrame {
 0 = <userdata>
 TextureUsedHeight2 = 183
 TopMargin = 13
 TopHeight = 80
 TextureWidth1 = 256
 LeftMargin = 0
 RightWidth = 94
 TexCoordY1 = 0.312500
 TextureWidth2 = 128
 PixelSnapDisabled = true
 TextureHeight2 = 256
 Background = <table> {
 }
 TexCoordY3 = 0.714844
 TexCoordX2 = 0
 TexCoordY2 = 0
 TextureHeight1 = 256
 TexCoordX3 = 0.734375
 MiddleWidth2 = 60
 TexCoordX1 = 0.312500
 TextureUsedWidth2 = 94
 RightMargin = 1
 MiddleWidth1 = 176
 LeftWidth = 80
 BottomMargin = 3
 BottomHeight = 183
}
(*temporary) = nil
(*temporary) = Texture {
 0 = <userdata>
 PixelSnapDisabled = true
}
(*temporary) = "HORIZONTAL"
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = 0
(*temporary) = "attempt to call method 'SetGradientAlpha' (a nil value)"

**Comment by statuskwolek** [comment]
SetGradientAlpha I think needs to be replaced with another function/API call -- I think Blizz replaced it

**Comment by GovtGeek** [comment]
In OutfitterUITools.lua change
`	self.Background.Shadow:SetGradientAlpha(
			"HORIZONTAL",
			1, 1, 1, 1,
			1, 1, 1, 0)`
(it's on multiple lines)
to
`	self.Background.Shadow:SetGradient(
			"HORIZONTAL",
			CreateColor(1, 1, 1, 1),
			CreateColor(1, 1, 1, 0))`
That should fix this one particular issue.

**Comment by Gogo1951** [comment]
Fixed in latest.
