### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by GregoryGH** [cdmichaelb/Outfitter#15]
1x Outfitter\OutfitterBar.lua:1210: attempt to call global 'GetProfessions' (a nil value)
Outfitter\OutfitterBar.lua:1210: in function `Activate'
Outfitter\OutfitterBar.lua:973: in function `SetIconFilter'
Outfitter\OutfitterBar.lua:957: in function `SetIconSetID'
Outfitter\OutfitterBar.lua:1049: in function <Outfitter\OutfitterBar.lua:1048>
...tter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua:1326: in function `?'
...rfaceOutfitter\Libraries/LibDropdown-1.0.lua:694: in function <...rfaceOutfitter\Libraries/LibDropdown-1.0.lua:683>
...rfaceOutfitter\Libraries/LibDropdown-1.0.lua:854: in function `OnClick'
...rfaceOutfitter\Libraries/LibDropdown-1.0.lua:372: in function <...rfaceOutfitter\Libraries/LibDropdown-1.0.lua:370>

**Comment by cdmichaelb** [comment]
I assume you have no professions? If so, will be fixed in next update.

**Comment by GregoryGH** [comment]
Nop, i have profs.

**Comment by cdmichaelb** [comment]
Ah, I see what happened, on wow classic they replaced GetProfessions with GetNumPrimaryProfessions. Will be fixed for real in next update.

**Comment by cdmichaelb** [comment]
Let me know if error persists.
