### ISSUE TITLE
Rogue Stealth outfit does not work

### ISSUE THREAD

**Issue by jackflagg** [cdmichaelb/Outfitter#17]
Title says it all. When my rogue goes into stealth nothing happens. When he comes out of stealth nothing happens.

**Comment by cdmichaelb** [comment]
I'll check for errors but I don't have a rogue so can't test. I'll see about leveling a rogue to test.

**Comment by cdmichaelb** [comment]
Will take some time, it doesn't work because there isn't any code written to detect stealth.

**Comment by Packuh** [comment]
Hi, I just downloaded this addon specifically because of the need to change weapons in invisible mode of the Rogue. But this function does not work.

**Comment by cdmichaelb** [comment]
This may be fixed in the next version. Just have a few other changes to polish off before pushing.

**Comment by cdmichaelb** [comment]
Implemented, reopen if it doesn't fix it.
