### ISSUE TITLE
Needs Hit

### ISSUE THREAD

**Issue by Gogo1951** [cdmichaelb/Outfitter#2]
Hey Guys,

Love that you've brought back Outfitter!

Especially love that you can build sets off Pawn scores!

When building a set, you can add all sorts of abilities... but it's missing hit. I feel like at some point hit was dropped from the game, and you've pulled the version of Outfitter over after those changes. Can you add hit back again?

Thanks!

**Comment by cdmichaelb** [comment]
Yes, that's actually my current project. Trying to get Resistances working
too.

Everything seems to work using pawn weights though. Are you able to use hit
in pawn?

**Comment by Gogo1951** [comment]
I just want to be able to say, "Build the best Pawn set that also has a hit of at least x%." 

Appears I can do that with STR and such now, Pawn Weight + any other stat. It'd be great to be able to do it with hit as well.

**Comment by Gogo1951** [comment]
Works great, thanks!

**Comment by cdmichaelb** [comment]
I just found a bug, not sure what is causing it. The resistance set generation worked on my test alt, but it's not working on my main.

**Comment by Gogo1951** [comment]
Yeah it's behaving weird now. It did work the first time I used it. But now I'll add in a Pawn + Hit >= hit cap on that toon, and there's enough hit gear to get there... and it says calculating, and comes up with an outfit... but doesn't change any of the gear to meet hit conditions. Needs work. (=

**Comment by LandonStewart** [comment]
> Yeah it's behaving weird now. It did work the first time I used it. But now I'll add in a Pawn + Hit >= hit cap on that toon, and there's enough hit gear to get there... and it says calculating, and comes up with an outfit... but doesn't change any of the gear to meet hit conditions. Needs work. (=

https://github.com/cdmichaelb/Outfitter/issues/2#issuecomment-571898016

**Comment by Mizzajl** [comment]
Rebuilding a set for melee hit does currently not seem to work. when its fixed will it take set bonuses into account? like black dragonscale set for example.

**Comment by cdmichaelb** [comment]
> 
> 
> Rebuilding a set for melee hit does currently not seem to work. when its fixed will it take set bonuses into account? like black dragonscale set for example.

Yes, it should.

A work around for now is using Pawn. And personally, I think it's a better option in the first place since you can fine tune your settings.

**Comment by Gogo1951** [comment]
Closing this as you have a Pawn integration that solves the issue. But... please see my other ticket around Pawn not quite working perfectly. Thanks!

**Comment by Mizzajl** [comment]
with pawn you can't really set a cap target for hit chance, would be really helpfull if this was possible
