### ISSUE TITLE
Automation Script "Has buff" not working

### ISSUE THREAD

**Issue by justthompson** [cdmichaelb/Outfitter#20]
I created a Gear set that would swap weapons on my mage when i gain the Evocate buff.

To test on another character, I also created a Gear set on my pally to swap shields when I gain the buff "Holy Shield"

On both characters, when either buff is gained, the automation does not take place.

![image](https://user-images.githubusercontent.com/66805144/84445418-956f3d80-ac09-11ea-8bd8-78893216ef69.png)

**Comment by ghost** [comment]
Can confirm. The "dining" automation doesn't work either.

**Comment by cdmichaelb** [comment]
justthompson, are you attempting to automate these swaps during combat? Because blizzard has completely blocked that functionality from addons.

**Comment by justthompson** [comment]
Outside of combat for the Evocate buff.

**Comment by justthompson** [comment]
Also when testing with the Holy Shield buff on my Paladin, I was also out of combat.

**Comment by xysis00** [comment]
I had a similar issue and this change appears to have fixed it:

In [Outfitter.lua#4114](https://github.com/cdmichaelb/Outfitter/blob/master/Outfitter.lua#L4114), change
```lua
local vName, _, vTexture, _, _, _, _, _, _, _, vSpellID = UnitBuff("player", vBuffIndex)
```

to
```lua
local vName, vTexture, _, _, _, _, _, _, _, vSpellID = UnitBuff("player", vBuffIndex)
```

which matches the API documentation found [here](https://wow.gamepedia.com/API_UnitBuff#Returns).

That performs the lookups with expected values and enables any corresponding state.

**Comment by cdmichaelb** [comment]
Thanks, I'll test and implement that in the next update. A lot of my issues
have been exactly this, API changes. Sadly I think outfitter was abandoned
some time ago, so there were quite a few out of date api usages in it and
if they don't throw an error it's hard to pinpoint sometimes.

**Comment by justthompson** [comment]
On a side note, if you can get the addon working, Great.
However, i have found out that you cannot swap gear when channeling Evocate.
So even if the addon script "Has buff" was working, I cannot do what I was wanting.
Which was; to swap to weapons with high amounts of Spirit to get more yield from Evocate.
Instead I will have to swap weapons 1st, then cast evocate, and swap back after Evocate finishes.

**Comment by cdmichaelb** [comment]
Implemented the hasbuff fix.
