### ISSUE TITLE
Outfitter Classic: De-equipping my offhand sometimes

### ISSUE THREAD

**Issue by Nomar111** [cdmichaelb/Outfitter#22]
Hi there! I am using several accessories outfits that i switch around a lot in PVP. I deactivated all weapon slots in all these outfits, but sometimes Outfitter still de-equips my offhand when i switch outfits. Sadly i couldn't reliably reproduce the issue yet. Do you have any idea/lead for me what i could check or try out to get to the root of the problem? So far i deactivated all scripts and also de-selected the weapon slots in any outfit i use.

edit: i was actually able to reproduce the issue. i deleted all my outfitter savedvariables and started from scratch with 2 accessorie outfits that contain all items but the weapon mainhand/offhand/relic (im a druid). then i equip first outfit and equipt (by macro, not with outfitter) a 2 handed weapon. afterwards i equip (per macro again) main hand mace and Ancient Cornerstone Grimoire in offhand (usable item with 30 seconds equip-cooldown). then i go into stealth and switch to the second accesorie outfit -> suddenly my offhand is empty. no scripts used whatsoever (i even deactivated scripts in options). all other outfits (except for those 2) i deleted before.

edit2: i looked around a bit in your tables and found 2 tables CurrentInventoryOutfit and CurrentOutfit which both don't show "Ancient Cornerstone Grimoire" (my equipped offhand item) correctly. Like i got the item equipped, but "SecondaryHandSlot" shows 0 everywhere. all other items i have equipped are listed correctly. maybe that helps...

**Comment by xysis00** [comment]
I had a similar issue and this change appears to have fixed it:

In [Outfitter.lua#L3962](https://github.com/cdmichaelb/Outfitter/blob/a5bd14560741d2ebeb82bd4d8968678fb9aa30d1/Outfitter.lua#L3962), change
```lua
local vMainHandItem = pPreviousOutfit:GetItem("MainHandSlot")
```

to
```lua
local vMainHandItem = self.CurrentInventoryOutfit:GetItem("MainHandSlot")
```

That makes the check below against the main hand in your current outfit:

```lua
if self:ItemUsesBothWeaponSlots(vMainHandItem) then
    vSkipSlot = true
end
```

Which means it doesn't skip the off-hand slot if your previous outfit couldn't have one equipped.

**Comment by cdmichaelb** [comment]
I implemented xysis00's change, let me know if it helps Nomar111.

**Comment by Nomar111** [comment]
@xysis00: thanks man, you rock! seems to have fixed my issue <3

@cdmichaelb : thanks for hotfixing so fast!

**Comment by Nomar111** [comment]
Fixed :)
