### ISSUE TITLE
[SOLVED] FPS dropp when hovering over items in the bag

### ISSUE THREAD

**Issue by Konst0** [cdmichaelb/Outfitter#23]
[SOLVED] The issue is suddenly gone, don't know why.

When having this addon (outfitter) enabled, it creates FPS drop when hovering over items in the bag. Also creates huge FPS drop that lasts for like 1 second when swapping sets.

**Comment by cdmichaelb** [comment]
Sounds like a negative interaction with another addon. Any error messages?

**Comment by Konst0** [comment]
I turned all addons off and only enabled outfitter when I tested earlier, but now when I test again the issue is gone, so weird.
