### ISSUE TITLE
Ammo

### ISSUE THREAD

**Issue by danjohnso** [cdmichaelb/Outfitter#24]
The ammo slot is not included in outfits which make swapping outfits with a gun vs a bow an extra step to remember that I usually forget until I try to shoot.  Would it be possible to include ammo slot in the outfit configuration for relevant classes?

**Comment by cdmichaelb** [comment]
This may be fixed in next update. Let me know.

**Comment by cdmichaelb** [comment]
Had to revert this fix, it broke other stuff.

**Comment by Denziz** [comment]
> Had to revert this fix, it broke other stuff.

What stuff did it break? Would love to have this added since I am swapping between gun and bow and also forget to swap out the ammo haha :D
