### ISSUE TITLE
Set icon changes once swapping different trinket

### ISSUE THREAD

**Issue by Denziz** [cdmichaelb/Outfitter#25]
Hey mate! I will start by saying that I absolutely love this addon, it is my favorite equipment addon for sure. The problem I have that is kind off bothering me is when I click on for example my Broodlord set and then swap out some trinkets (Pre-pop Lifegiving gem and then swap it out to Drake Fang Talisman) it shows on minimap icon the DFT icon, could you please add a feature to disable this somehow? :)

Image showing it better.
https://imgur.com/a/xR00CKn

Kind regards Denziz.

**Comment by cdmichaelb** [comment]
Is it changing after you've set an icon, or are you letting it set the icon entirely on it's own. You can set the icon [here](https://i.imgur.com/KVNRFS8.png).

**Comment by Denziz** [comment]
Ye I have set the icon to Mortal Strike, but I don't want it to ever change even if I swap out trinkets etc.

So in my image for example that icon shows when I have not modified anything in that set, however when I swap trinkets it changes the icon which I do not want :)

If it is possible to make this happen I would really, really appreciate it so much!

**Comment by Denziz** [comment]
Basically I don't want the Icon to ever change from it's already set icon, the icon changes whenever I swap something out that doesn't belong to that set, for example the trinkets in my first post.

**Comment by cdmichaelb** [comment]
I'm unable to replicate this error, could you record a video or gif by chance?
