### ISSUE TITLE
Outfitter Bar Issue

### ISSUE THREAD

**Issue by Kriptoker** [cdmichaelb/Outfitter#26]
The outfitter bar was missing, so I tried to turn it off and back on from the addon settings (uncheck and check the box). And got the below error:

*Edit*
This is with the latest version from Curse, which reports it as 1.2.7, not sure why the addons list below still shows it at 1.2.0
*Edit*

Date: 2020-07-03 16:05:30
ID: 3
Error occured in: Global
Count: 6
Message: ..\AddOns\Outfitter\OutfitterBar.lua line 219:
   attempt to index field 'Settings' (a nil value)
Debug:
   (tail call): ?
   [C]: ?
   Outfitter\OutfitterBar.lua:219: SetShowOutfitBar()
   [string "*:OnClick"]:2:
      [string "*:OnClick"]:1
Locals:
(*temporary) = "LeftButton"
(*temporary) = false
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ActionBarSaver, v
  AddOnSkins, v4.40
  AdiBags, vv1.9.20-classic
  AdiBagsOutfitter, vv1.5.5-classic
  AdvancedInterfaceOptions, v1.3.4
  AskMrRobotClassic, v2
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AutoAmmo, v1.1.3
  AutoCombatLogger, v8.3.2
  AVQ, v28
  BadBoy, vv1-classic
  BattlegroundTargets, v11304-4
  BattleInfo, v@project-version
  BCT, v1.35
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BestInSlotClassic, v2.5.2
  BetterVendorPrice, vv1.13.04
  ClassicLootAssistant, v
  DBMCore, v1.13.51
  DBMDefaultSkin, v
  DBMPvP, vr91
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dismounter, v1.2.1
  ElvUI, v1.24
  ElvUIBenikUIClassic, v1.12
  ElvUIDTBars2, v1.0
  ElvUIExtraDataTextsClassic, v1.0.2
  ElvUILocationPlus, v1.03
  ElvUINutsAndBoltsClassic, v1.02
  ElvUIPVPDT, v1.00
  ElvUIQuestXPClassic, v1.0.0
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  FarmHud, v8.3-6-classic-release
  FarmLog, vv1.19
  FishingBuddy, v0.7.3 Beta 5
  GatherMate2, v1.45.5
  GeartoGearPlanner, vv1.3.7
  GigaAutoResourcesTracker, v1.1.0
  Hemlock, v1.1.2
  HHTD, v2.4.9.5
  honorspy, v1.7.3
  HPH, v2.13
  Immersion, v1.2.3
  InFlightLoad, v1.13.005
  Informant, v8.2.6374 (SwimmingSeadragon)
  LFGMatchMaker, v1.0.8
  MikScrollingBattleText, v5.7.149
  Molinari, v80300.66-Release
  NovaWorldBuffs, v1.66
  Outfitter, v1.2.0
  Plater, vPlater-1.13.4.81-Classic
  ProjectAzilroka, v1.67
  QuestAnnounce, v8.0.2.1
  Questie, v6.0.0
  RangeDisplay, vv4.9.1
  RareAware, v1.0
  RCLootCouncilClassic, v0.10.1
  RecipeRadarClassic, v1.0.0.23
  RollTrackerClassic, v2.21
  Routes, vv1.6.3
  SkullMe, v3.0.4
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpeedyMount, v1.1.2
  Spy, v1.1.0
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv11304-1.1.2
  totalRP3, v1.6.13
  totalRP3Data, v
  WeakAuras, v2.17.8
  WeakAurasCompanion, v1.1.0
  WeaponSwingTimer, v4.1.0
  WIM, v3.8.11
  WoWPro, v1.13.4-B2
  WoWProAchievements, v1.13.2I
  WoWProDailies, v1.13.2I
  WoWProLeveling, v1.13.4-B2
  WoWProWorldEvents, v1.13.2I
  XLoot, v8.1-1
  XLootFrame, v8.1-1
  XLootGroup, v8.1-1
  XLootMaster, v8.1-1
  XLootMonitor, v8.1-1
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=ac1)

**Comment by Kriptoker** [comment]
I also got an error from AddonSkins, from ElvUI, with Outfitter, so I turned that seting off in ElvUI. And did a /reloadui, and got the below error:

Date: 2020-07-03 16:13:25
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Outfitter\OutfitterOutfits.lua line 252:
   attempt to index local 'vItem' (a string value)
Debug:
   (tail call): ?
   [C]: ?
   Outfitter\OutfitterOutfits.lua:252: CheckOutfit()
   Outfitter\Outfitter.lua:6227: CheckDatabase()
   Outfitter\Outfitter.lua:4705: Function()
   ...fitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua:242: OnUpdate2()
   ...fitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua:178: OnUpdate()
   ...fitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua:20:
      ...fitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua:20
Locals:
(*temporary) = 9.945001
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ActionBarSaver, v
  AddOnSkins, v4.40
  AdiBags, vv1.9.20-classic
  AdiBagsOutfitter, vv1.5.5-classic
  AdvancedInterfaceOptions, v1.3.4
  AskMrRobotClassic, v2
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AutoAmmo, v1.1.3
  AutoCombatLogger, v8.3.2
  AVQ, v28
  BadBoy, vv1-classic
  BattlegroundTargets, v11304-4
  BattleInfo, v@project-version
  BCT, v1.35
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BestInSlotClassic, v2.5.2
  BetterVendorPrice, vv1.13.04
  ClassicLootAssistant, v
  DBMCore, v1.13.51
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dismounter, v1.2.1
  ElvUI, v1.24
  ElvUIBenikUIClassic, v1.12
  ElvUIDTBars2, v1.0
  ElvUIExtraDataTextsClassic, v1.0.2
  ElvUILocationPlus, v1.03
  ElvUINutsAndBoltsClassic, v1.02
  ElvUIPVPDT, v1.00
  ElvUIQuestXPClassic, v1.0.0
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  FarmHud, v8.3-6-classic-release
  FarmLog, vv1.19
  FishingBuddy, v0.7.3 Beta 5
  GatherMate2, v1.45.5
  GeartoGearPlanner, vv1.3.7
  GigaAutoResourcesTracker, v1.1.0
  Hemlock, v1.1.2
  HHTD, v2.4.9.5
  honorspy, v1.7.3
  HPH, v2.13
  Immersion, v1.2.3
  InFlightLoad, v1.13.005
  Informant, v8.2.6374 (SwimmingSeadragon)
  LFGMatchMaker, v1.0.8
  MikScrollingBattleText, v5.7.149
  Molinari, v80300.66-Release
  NovaWorldBuffs, v1.66
  Outfitter, v1.2.0
  Plater, vPlater-1.13.4.81-Classic
  ProjectAzilroka, v1.67
  QuestAnnounce, v8.0.2.1
  Questie, v6.0.0
  RangeDisplay, vv4.9.1
  RareAware, v1.0
  RCLootCouncilClassic, v0.10.1
  RecipeRadarClassic, v1.0.0.23
  RollTrackerClassic, v2.21
  Routes, vv1.6.3
  SkullMe, v3.0.4
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpeedyMount, v1.1.2
  Spy, v1.1.0
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv11304-1.1.2
  totalRP3, v1.6.13
  totalRP3Data, v
  WeakAuras, v2.17.8
  WeakAurasCompanion, v1.1.0
  WeaponSwingTimer, v4.1.0
  WIM, v3.8.11
  WoWPro, v1.13.4-B2
  WoWProAchievements, v1.13.2I
  WoWProDailies, v1.13.2I
  WoWProLeveling, v1.13.4-B2
  WoWProWorldEvents, v1.13.2I
  XLoot, v8.1-1
  XLootFrame, v8.1-1
  XLootGroup, v8.1-1
  XLootMaster, v8.1-1
  XLootMonitor, v8.1-1
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=ab2)

**Comment by cdmichaelb** [comment]
I reverted the ammo fix, that was causing your issue. Also fixed version reported in game.
