### ISSUE TITLE
Rogue (only) toon scripts fail, other work great

### ISSUE THREAD

**Issue by Wutapro** [cdmichaelb/Outfitter#27]
1st, THANK YOU, Outfitter is awesome! oddly, with my rogue, scripts just randomly failed, it's not even the issue posted above with stealth, its all the time now. I deleted all sets/scripts, except 'Normal' & 'Birthday Suit' so now it seems to automatically swap me to 'naked' when leaving an instance.
Is there a reset button for the app? or should I delete it all and just redo all 10 toons 3-4 outfits? Thx
(This is WOW Classic version)

**Comment by cdmichaelb** [comment]
There isn't really a soft reset, you can reset everything with the below
method.

Can you elaborate on randomly failed? You mean the fact that it's swapping
to birthday suit? Are you certain there isn't a script setup to equip
birthday suit on any conditions?  I can't really think what could be
causing an issue like that other than a rogue script, I haven't personally
experienced it.

If you installed via the twitch client you can find the addon on it, Right
Click -> Delete Settings (Saved Variables). If you don't use twitch, go
into your wow folder /WTF/AccountName/Server/Character/SavedVariables and
find Outfitter.lua and delete it.

**Comment by Wutapro** [comment]
Thanks for the reply.  I guess the use of random was in itself random. So I
simply meant it worked for a while, then didn't.  And I can't think of what
I did to change it.  And no there's no script I created to equip Bday, I
left it default.
But again last night it auto equipped Bday as I exited dungeon, but did not
equip Normal as I re- entered.
One more odd thing, that makes me wonder if it's a glitch with WOW, when I
did re-equip with Normal, it did not show my foot slot item in game. My
team said "do you know you're barefoot?" And it looked that way, but I did
have an item equipped.
