### ISSUE TITLE
Druid: Equips Items when shifting into Caster Form

### ISSUE THREAD

**Issue by ap0yuv** [cdmichaelb/Outfitter#28]
I defined the that no Slots are used in Caster Form , i even deactivated the Automation Script for Caster Form.

Yet still everytime i shift out of e.g. Cat Form into Caster Form, Outfitter always equips the last saved "Caster Form" Outfit.

Any idea why that happens ?

i am happy to assist. Maybe someone can point me to where in the Code i need to start looking ?

**Comment by cdmichaelb** [comment]
Not quite sure of an easy way to fix this. But you could save your cat form into your caster form. That way it won't swap gear when you switch.
