### ISSUE TITLE
Character sheet messed up with addon enabled, fine without

### ISSUE THREAD

**Issue by nwardoh** [cdmichaelb/Outfitter#29]
With the addon enabled my character screen is doing this

![image](https://user-images.githubusercontent.com/49296584/87628247-1f716100-c6f6-11ea-973c-fae4e1beafc4.png)

**Comment by TimurBorn** [comment]
Delete all settings. It did not work via Twitch for me, so I searched for "outfitter" in the WTF folder and deleted them manually. Once done the character screen was fixed again.

**Comment by TimurBorn** [comment]
Delete all settings. It did not work via Twitch for me, so I searched for "outfitter" in the WTF folder and deleted them manually. Once done the character screen was fixed again.

**Comment by cdmichaelb** [comment]
This is an interaction with Elvui or other similar addons.

**Comment by nwardoh** [comment]
Will it be fixed?

**Comment by cdmichaelb** [comment]
Nothing I can do in the short term, I think it has to do with whatever they
use for skinning (making the ui look sleek). I could try some ideas.

**Comment by Weissrolf** [comment]
Edit: Try disabling Outfitter skinning in AddonSkins first.

Outfitter worked with ElvUI a short time ago, so either of the two changed something. I deleted everything "Outfitter" in the WTF folder (aka settings). This fixed the problem, so resetting the settings should do.

**Comment by Weissrolf** [comment]
Sorry, turns out that I did two things: If you use AddonSkins then you need to go into its settings and disable Outfitter skinning. Too bad that these two don't seem to get along.

**Comment by nwardoh** [comment]
Thank you, I will give that a shot. I really hate itemrack!
