### ISSUE TITLE
OutfitterButton offset looks not correct

### ISSUE THREAD

**Issue by lorem-ipsum-dolor-sit** [cdmichaelb/Outfitter#3]
The position from the outfitter looks a bit out of space ;)

<img src="https://user-images.githubusercontent.com/5527697/72205310-ed9aeb80-3481-11ea-9b95-7ba28f9985d3.png" width="200">

### OutfitterButton
https://github.com/cdmichaelb/Outfitter/blob/a5d65ad9f747557d84ecc0e7c0a2cf355de0d699/Outfitter.xml#L587
`<AbsDimension x="-28" y="-42"/>`
### OutfitterFrame
https://github.com/cdmichaelb/Outfitter/blob/a5d65ad9f747557d84ecc0e7c0a2cf355de0d699/Outfitter.xml#L611
`<AbsDimension x="-34" y="-48"/>`

WIth my changes it looks a bit better.
<img src="https://user-images.githubusercontent.com/5527697/72205328-18853f80-3482-11ea-85a8-75cd678f007d.png" width="200">

**Comment by cdmichaelb** [comment]
It is, thanks. I suck at UI elements. Do you want to do a pull request or
do you want me to just incorporate it?

**Comment by lorem-ipsum-dolor-sit** [comment]
a pull request is pending 👍
