### ISSUE TITLE
[Error][outfitter] No events found for Hawk

### ISSUE THREAD

**Issue by dman925625** [cdmichaelb/Outfitter#32]
Getting that error whenever I switch aspects on my hunter.  Using the classic version and updated it recently (this week) through the twitch app.  Typing "/outfitter errors off" doesn't stop showing that error, and I don't know what to do to make it stop popping up

**Comment by ksulli10** [comment]
I am getting the same error.

**Comment by cdmichaelb** [comment]
I will check this in the morning.

**Comment by valepu** [comment]
Same problem here

**Comment by cdmichaelb** [comment]
So I looked at this, it should be working. No idea why it isn't. I'll need to level a hunter a bit to see if I can replicate it.

**Comment by ksulli10** [comment]
It happens any time the game applies the Aspect of the Hawk to your character, which includes _hidden_ times where the aspect gets re-applied transparently (like changing instances or initially logging in to the game.)

**Comment by MasterLeecher** [comment]
I have the same error. Can you look at it please?

Thanks for your help!

**Comment by Paroyer** [comment]
Same error it's a pain to play Hunter with this

**Comment by GovtGeek** [comment]
I was able to get the error to go away by adding one line to Outfitter.lua.

After Line 956 (Should say "Feigning ...") try adding this:
Hawk = {Equip = "HAWK", Unequip = "NOT_HAWK"},

I don't know if it breaks anything else, since my hunter is only 30, but it doesn't pop up anymore!

**Comment by cdmichaelb** [comment]
Reopen if issue isn't resolved.
