### ISSUE TITLE
Have to click multiple times to equip full outfit

### ISSUE THREAD

**Issue by Shamatix** [cdmichaelb/Outfitter#33]
Hi there,

There is 2 bugs and I will do my best to describe them.

First Bug - If I have 2 of the same rings, it only equips one of them until I click the outfit again.
So in 1 set, lets call it NR1, I have equipped 1x Nature resistance ring, in another set, lets call it NR2, I have 2 of the same Nature Resistance ring equipped.
So if I have NR1 set equipped and I press to equip my set NR2, it bugs out and only has 1 of the NR rings equipped, if I however click again, it equips the second? See gif below.
https://i.imgur.com/5LA9atl.gif

Second bug - If I have 2 sets using the same trinket, but in the first set my trinket is in Slot 1, and in my second set the same trinket is in Slot 2, it cant swap out the trinket - Unsure if this one requires a vid.

Hope you can fix these 2 issues as they are both very annoying.

**Comment by cdmichaelb** [comment]
I'll have to look at those. I hadn't considered the first issue, I have an idea of how to fix it but I'll need to find some rings that I can test it with.

2nd issue, I'll have to look at.
