### ISSUE TITLE
Using macro to equip sets

### ISSUE THREAD

**Issue by matthias8422** [cdmichaelb/Outfitter#34]
Is there a way to use a macro to equip sets, for instance i want to equip the druid cenarion set for the 3 piece bounus and cast thorns then requip my + healing gear. the macro would go somethin like this...

/equipset cenarion
/cast thorns
/equipset healing

Is there a way to do this?

**Comment by beldense** [comment]
Try:

/outfitter wear cenarion
/cast thorns
/outfitter wear healing
