### ISSUE TITLE
"Outfit Display" - removed with transmog?

### ISSUE THREAD

**Issue by beldense** [cdmichaelb/Outfitter#35]
So this is one of the nice features of using some gearsets, you can set to show helm/cloak etc but it seems to be missing from classic version as it is an fork from retail, in retail you have to transmog away your helm/cloak if you dont want that anymore...

The best version I could find is probably at the bottom of this page, version 5.4.2
https://www.wowinterface.com/downloads/info5467-Outfitter.html#other

in this zip, Outfitter/Outfitter.lua, line 2127
`elseif UIDROPDOWNMENU_MENU_VALUE == "DISPLAY" then`

Tried to find something similiar to this in classic version, but it seems like the original creator has new ways of doing this, I'm not very experienced, just decently enough to understand but I guess it's been patched and needs another way of doing this...

Image "Outfit Display":
https://cdn-wow.mmoui.com/preview/pvw19791.png

Would be nice if you could patch a feature similiar to this in classic ^^
I'll do some more digging if it's gonna be anything to help...

**Comment by Belden1** [comment]
I have done some research and added core functionality in, still needs some work on it...

https://github.com/Belden1/Outfitter/commit/2c46b66aecae309b3e5a3e94c76f205a3654b1b1

have a look, let me know if change anything or push it so you can fix it ^^

**Comment by beldense** [comment]
https://github.com/Belden1/Outfitter/commit/7091fe3c78f456f76e17197f1ae768285838f538

I have tried it out and it works! :)
