### ISSUE TITLE
Item off CD announcement

### ISSUE THREAD

**Issue by YoungGooby** [cdmichaelb/Outfitter#37]
I have a separate addon to track my CD's including my useable items like trinkets. Is it possible to add a toggle option for the announcment when my trinkets are off CD? I'd just like to eliminate the redundancy.

**Comment by beldense** [comment]
Can you explain more of what is happening, maybe some image of the text etc?

**Comment by YoungGooby** [comment]
Sure, so I am using your addon and the trinket script. When the trinkets I use come off CD it announces it like in the SS below. I believe the blue text at the top is outfitter and it makes a sound. 

https://i.imgur.com/3VKDzcZ.jpeg

I am wondering if it is possible to toggle the accouncement and/or the sound.

**Comment by cdmichaelb** [comment]
That's not this addon.

You can type /fstack and mouseover it when it displays, try to see what addon it is. If it is this one, tell me what it says if you can and I'll track it down.

**Comment by YoungGooby** [comment]
You're right. It was item rack, I forgot i reinstalled it to check something. Sorry for wasting your time.
