### ISSUE TITLE
Armor as a stat

### ISSUE THREAD

**Issue by bluetardis** [cdmichaelb/Outfitter#38]
Is it possible to get "Armor" added as a stat when generating outfits please.

**Comment by cdmichaelb** [comment]
I'll see about adding it, but I want to suggest you use Pawn integration instead and use a Pawn stat weight to generate outfits. It's vastly superior to the outfitter implementation.

**Comment by Gogo1951** [comment]
Just use Pawn, and then build your sets around Pawn values. Ezi pzi. (=

**Comment by cdmichaelb** [comment]
I'll likely be removing non-pawn set building, rather than attempting to fix/build the custom set building code. If anyone wants to do it and do a PR feel free, otherwise I'm closing the issue for now.
