### ISSUE TITLE
Mounted conditional and Equip on Target

### ISSUE THREAD

**Issue by YoungGooby** [cdmichaelb/Outfitter#39]
Hey, sorry to make another post so recently after my last idiotic one. I am trying to get a couple things to work properly.

First, I am using the default script to equip the AD trinket when in EPL, WPL, Scholo, and strat. The script works fine and as intended when in all these zones. However, I am wondering if it is possible to add a conditional that when mounted in EPL or WPL it uses the mounted set then when dismounting goes back to the zone-specific set. 

Second, I am really struggling to get the equip on target script to work. I want the script to equip certain trinkets when targetting certain bosses. I have been testing the script on random mobs near SW and it doesn't seem to work at all. Basically, I want to wear my "normal" outfit then upon targeting a specific mob switch to the equip on target set, then when the mob is dead or when not targeting it switch back to normal. What can I do to troubleshoot this? Further, do I need to make a separate outfit per boss or is it possible to have a string of potential boss names? 

I have tried to mess with both of these a little myself but I don't know LUA code at all. If you guys have a discord I'd be happy to post this in there instead of using this if that is preferred.

**Comment by cdmichaelb** [comment]
Mounted set should be overriding any other set already. The exception is in dungeons, which you can toggle in the script settings for mounted set.

Equip on target isn't functioning correctly atm. I'll look more into it after naxx progression is over.
