### ISSUE TITLE
Spirit outfit script fails on my rogue

### ISSUE THREAD

**Issue by Suomitikru** [cdmichaelb/Outfitter#40]
I've been trying to get the string to work but can't. It says: 

"Couldn't activate script for Spirit outfit for offcombar healing"
"[string "Script for Spirit outfit for offcombat healing"]:28: malformed number near '0.5end'"

What could be the issue and the fix for this?

**Comment by Suomitikru** [comment]
Yeah rogues don't have mana. Look at me not reading what the script is for

**Comment by cdmichaelb** [comment]
Can I ask what you were trying to use it for? I mean technically spirit is good for HP regen out of combat, there could be some argument that it would be useful for leveling.

**Comment by Suomitikru** [comment]
> Can I ask what you were trying to use it for? I mean technically spirit is good for HP regen out of combat, there could be some argument that it would be useful for leveling.

Yes, you're absolutely correct. I tried to set it up so I can put the spirit gear on automatically while going from mob to another
