### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Slimmer2** [cdmichaelb/Outfitter#41]
Message: ...dOns\Outfitter\Libraries/MC2EventLib/MC2EventLib.lua:88: Attempt to register unknown event "UNIT_ENTERED_VEHICLE"
Time: Fri Aug 28 10:33:49 2020
Count: 1
Stack: ...dOns\Outfitter\Libraries/MC2EventLib/MC2EventLib.lua:88: Attempt to register unknown event "UNIT_ENTERED_VEHICLE"
[C]: in function `RegisterEvent'
...dOns\Outfitter\Libraries/MC2EventLib/MC2EventLib.lua:88: in function `RegisterEvent'
Interface\AddOns\Outfitter\OutfitterScripting.lua:1861: in function `RegisterEvent'
Interface\AddOns\Outfitter\OutfitterScripting.lua:1746: in function `ActivateScript'
Interface\AddOns\Outfitter\OutfitterScripting.lua:1796: in function `ActivateAllScripts'
Interface\AddOns\Outfitter\Outfitter.lua:4936: in function `Function'
...fitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua:242: in function `OnUpdate2'
...fitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua:178: in function `OnUpdate'
...fitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua:20: in function <...fitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua:20>

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
 EventLib = <table> {
 }
}
(*temporary) = "UNIT_ENTERED_VEHICLE"

**Comment by cdmichaelb** [comment]
Can you tell me what you were doing when this happened?

**Comment by Slimmer2** [comment]
I only log in to my Char.
German client

**Comment by Slimmer2** [comment]
I found the error. I deleted the file outfitter.lua and outfitter.lua.bak under WFT folder and the error is gone
