### ISSUE TITLE
Char Frame Messed up in Combat

### ISSUE THREAD

**Issue by Kriptoker** [cdmichaelb/Outfitter#43]
Hi, when in combat, opening the character frame causes it to get all wonkey.

The Outfitter Character frame button moves to the top right of the screen and the whole bottom of the Character UI Frame goes to the top of the screen.

Here is a link to an image of what I am seeing. https://ibb.co/7VmmBRp

I am also using ElvUI with BenikUI.

**Comment by DelVision** [comment]
Having the same issue, and my guess is that it has something to do with the outfitter button (currently located on top right of the character window).. It used to be all  the way to right side of the whole screen but now it's moved to the character window and then this bug happened.

It looks fine if you open second window like spellbook for example, but then if you close the windows and open character frame again the same issue happens.

**Comment by cdmichaelb** [comment]
You screenshot expired so I can't look at it, but it's known to have issues with elvui.
