### ISSUE TITLE
Aspect of the hawk triggers Error

### ISSUE THREAD

**Issue by Syth141** [cdmichaelb/Outfitter#48]
Whenever I use Aspect of the Hawk I get an error saying

[ERROR] [Outfitter] No events found for Hawk

I am a fan of the add-on, but this error is very obnoxious.

Thank you

**Comment by Zwoxlol** [comment]
Yes same for me and a other Guildi.

**Comment by GovtGeek** [comment]
I was able to get the error to go away by adding one line to Outfitter.lua.

After Line 956 (Should say "Feigning ...") try adding this:
	Hawk = {Equip = "HAWK", Unequip = "NOT_HAWK"},

I don't know if it breaks anything else, since my hunter is only 30, but it doesn't pop up anymore!
