### ISSUE TITLE
Item shows as missing when it's already equipped

### ISSUE THREAD

**Issue by TheDreadGazeebo** [cdmichaelb/Outfitter#57]
See screenshots. was able to fix this by swapping to a different pair of boots, saving the outfit, then swapping the correct boots back in and saving outfit again.
![WoWScrnShot_031221_143706](https://user-images.githubusercontent.com/80544178/110990330-2c0b8f00-8341-11eb-827c-0dcdfbd27f4e.png)
![WoWScrnShot_031221_143708](https://user-images.githubusercontent.com/80544178/110990337-2d3cbc00-8341-11eb-8e99-3026a47610d3.png)

**Comment by TheDreadGazeebo** [comment]
not sure if this is related to the previous issue I posted but it seems like a possibility.

**Comment by Gogo1951** [comment]
I haven't seen this issue, I assume it's been fixed. Please re-open this if you are still getting this error. Thanks!
