### ISSUE TITLE
TBC Version

### ISSUE THREAD

**Issue by TheAce84** [cdmichaelb/Outfitter#58]
Is there any plan for a TBC port?
Actual its not working ont TBC well

**Comment by cdmichaelb** [comment]
Yes. I was going to wait until after launch week to fix the bugs, but it's actually pretty bad so I'll be fixing it in the next few days instead.

**Comment by TheAce84** [comment]
Nice, Thanks for you answer

**Comment by Gogo1951** [comment]
This was done. (=
