### ISSUE TITLE
Dropdown not working in TBC

### ISSUE THREAD

**Issue by valepu** [cdmichaelb/Outfitter#59]
Hi,
The addon seems to work fine in TBC except for one issue, the dropdown menu (either from the minimap button or Titan panel) does not work, i receive this error:
```

3x ...tter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua:1431: DropDownMenu can't call Hide if not shown
[string "=[C]"]: in function `assert'
[string "@Outfitter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua"]:1431: in function `Hide'
[string "@Outfitter\OutfitterMinimapButton.lua"]:250: in function `ToggleMenu'
[string "*:OnMouseUp"]:1: in function <[string "*:OnMouseUp"]:1>

Locals:
(*temporary) = nil
(*temporary) = "DropDownMenu can't call Hide if not shown"

```

**Comment by cdmichaelb** [comment]
Thanks, there's a lot of issues. I'll be fixing it over the next few days.

**Comment by ap0yuv** [comment]
did you start yet , i personally did some minor changes in MC2UIElementsLib.lua so its working a bit atleast

**Comment by Gogo1951** [comment]
Please re-open if you're still having this issue. I believe it's been resolved.
