### ISSUE TITLE
Missing ranged slot

### ISSUE THREAD

**Issue by valepu** [cdmichaelb/Outfitter#6]
First of all, thanks for bringing this great addon to Classic!
I wanted to report that the ranged slot cannot be configured at the moment (I don't get the checkbox into it when making a set). I guess it has to do with the fact that it doesn't exist on retail

Thanks again

**Comment by sighres** [comment]
Will this issue be adressed soon? Addon would be perfect for me if i could switch the ranged slot.

**Comment by cdmichaelb** [comment]
A little note. I don't have a high level character for testing ranged slot, so let me know if there are any further issues.
