### ISSUE TITLE
Resize Outfitter bar

### ISSUE THREAD

**Issue by nickdekruijk** [cdmichaelb/Outfitter#63]
Thanks for updating Outfitter for TBC!

The only thing I struggle with is resizing the Outfitter bar. In retail (didn't use it in vanilla classic) you can just right click the left or right anchors and resize the buttons and change the background. This doesn't seem to work in TBC?

**Comment by cdmichaelb** [comment]
I'll add that to the list. Since we're on a more modern client in tbc that
should make a lot of things easier.

**Comment by ChristopherNewbound** [comment]
OutfitterBar.lua line 1373 needs to inherit from BackdropTemplate 
local vSettingsDialog = CreateFrame("Frame", "OutfitBarSettingsDialog", UIParent)

change to:
local vSettingsDialog = CreateFrame("Frame", "OutfitBarSettingsDialog", UIParent, "BackdropTemplate")

Then right clicking on outfitter bar anchors brings up UI to change size.

**Comment by cdmichaelb** [comment]
Fixed thanks.

**Comment by Gogo1951** [comment]
I haven't seen this issue, I assume it's been fixed. Please re-open this if you are still getting this error. Thanks!
