### ISSUE TITLE
Why delete the TBC toc?

### ISSUE THREAD

**Issue by beren12** [cdmichaelb/Outfitter#64]
The addon will never show as current now, and sites like curse won't mark it as tbc compat, or as classic compat if there's no classic toc...

**Comment by cdmichaelb** [comment]
It was actually deleted because curse was rejecting it. I'm unsure if they have an error on their site or what. But I believe these sites are reading the ToC for the version number and using that to list it as a TBC addon. It is properly showing up under TBC.

**Comment by Gogo1951** [comment]
I haven't seen this issue, I assume it's been fixed. Please re-open this if you are still getting this error. Thanks!
