### ISSUE TITLE
Mining/Herbalism automations not working - TBC Classic 2.0.2

### ISSUE THREAD

**Issue by justthompson** [cdmichaelb/Outfitter#65]
Automations for Herbalism and Mining do not seem to be working in the latest TBC Classic Build.
Tested both mining nodes and herbalism nodes. When the note has a Red or Orange skill level, Outfitted should automate switching gear, however it does not.

**Comment by cdmichaelb** [comment]
This may be fixed with latest version, let me know.

**Comment by justthompson** [comment]
Still does not appear to work in 2.0.4

**Comment by Gogo1951** [comment]
I haven't seen this issue, I assume it's been fixed. Please re-open this if you are still getting this error. Thanks!
