### ISSUE TITLE
Fishing Script set not unequipped during combat

### ISSUE THREAD

**Issue by ChristopherNewbound** [cdmichaelb/Outfitter#66]
Addon states that on entering combat the fishing script will unequip the set automatically.
This does not happen; writing a custom script to do so results in the set being unequipped but not until combat has finished; even though the fishing set in question is only the weapon / fishing rod and can therefore be changed during combat in TBC.

**Comment by cdmichaelb** [comment]
You can change weapons in combat, but not with an addon. 

Just to verify nothing changed in TBC I wrote a quick WA script:
1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'PickupInventoryItem()'.

It should still be able to function without changing in combat, there is a frame that is called when entering combat that is still out of combat for doing last minute things like gear swaps. So I will try to figure out why it isn't doing it on that frame.

**Comment by Gogo1951** [comment]
Yeah, you can personally change weapons but add-ons can't. We can't do anything about this.
