### ISSUE TITLE
"Rebuild for..." missing options

### ISSUE THREAD

**Issue by linkandzelda91** [cdmichaelb/Outfitter#67]
I just found out about the rebuild for function and it's amazing, but I'm having a problem where spell only contains spell hit (I would like to be able to build for sp for ex).

ranged is empty entirely but idc cuz I'm a mage lol

![image](https://user-images.githubusercontent.com/1525431/121824250-6d794680-cc70-11eb-9a87-0ad8710cb0bc.png)

**Comment by cdmichaelb** [comment]
I was working on fixing those but stopped because they were annoying. Some
work well, some don't work at all, I removed most of what didn't work. I
highly recommend downloading Pawn and using the pawn integration. It can
build sets based on pawn weights.

**Comment by linkandzelda91** [comment]
I'll check out pawn ty

**Comment by linkandzelda91** [comment]
okay so this is fun pawn has no way of stopping a stat weight when I hit a cap (so ex hit cap is a problem), but outfitter does and it seems to work.

so I'll combine a hit cap stat weight in outfitter with pawn weights for everything else lmao. ty


have you considered gutting all that options that pawn supports and just focusing on the things that pawn can't do (aforementioned hit cap)

**Comment by Gogo1951** [comment]
I haven't seen this issue, I assume it's been fixed. Please re-open this if you are still getting this error. Thanks!
