### ISSUE TITLE
Outfitter + Pawn Pala offhand

### ISSUE THREAD

**Issue by Padparadscha** [cdmichaelb/Outfitter#68]
Hi, I'm not shure if it is a problem with Pawn or Outfitter.
When I optimize for Pawn  Pala Tank, Outfitter try to equip a offhand Weapon. This is not possible and it also ignores Shields in the inventory.

**Comment by Gogo1951** [comment]
Does this for Warriors as well.

**Comment by Gogo1951** [comment]
I haven't seen this issue, I assume it's been fixed. Please re-open this if you are still getting this error. Thanks!
