### ISSUE TITLE
Outfitter Square Minimap button integration

### ISSUE THREAD

**Issue by Ameyia1809** [cdmichaelb/Outfitter#69]
I'm using ElvUI with Square Minimap.
The Outfitter button is about half way from middle  and minimap borders.

is there a way to "get minimap border" informations so it can use it instead of "regular circle" minimap defaults ?

![square minimap](https://user-images.githubusercontent.com/49327241/123286649-154a0c00-d4dc-11eb-9218-0b5618931f6d.jpg)

**Comment by Gogo1951** [comment]
Tagging into #84
