### ISSUE TITLE
Outfitter/VuhDo Smartcast Redemtion Issue

### ISSUE THREAD

**Issue by nargallegos** [cdmichaelb/Outfitter#70]
There is an issue where Vuhdo v3.124-tbcc-bc and Outfitter - Classic 2.0.4.TBCC together maybe causing Vuhdo's smartcast of Redemption for Paladins to fail. The issue was originally reported here: https://gitlab.vuhdo.io/vuhdo/vuhdo/-/issues/118

I can confirm that the bug still exists as I have turned down all addons except these two, and once Outfitter is disabled I am able to smartcast redemption out of combat. I am not too familiar with the code bases of either addon but I will look further into the issue to see if I can provide more information In the meantime I opened this up for documentation purposes and hopefully someone who knows about about either addon can spot something.

**Comment by nargallegos** [comment]
Seems like the issue may be @ line 7895.
```
function GetSpecialization()
	--local _, vName = GetSpecializationInfo(pIndex)
	local vName1, _, vTab1 = GetTalentTabInfo(1)
	local vName2, _, vTab2 = GetTalentTabInfo(2)
	local vName3, _, vTab3 = GetTalentTabInfo(3)
	if vTab1 >= vTab2 and vTab1 >= vTab3 then
		
		--print("vTab1")
		return "1"
	elseif vTab2 >= vTab1 and vTab2 >= vTab3 then
		
		--print("vTab2")
		return "2"
	elseif vTab3 >= vTab1 and vTab3 >= vTab2 then
		
		--print("vTab3")
		return "3"
	elseif nil then
		return nil
	else
		
		--print("vTab4")
		return "4"
	end
	--return vName
end
```


This function overrides the return value into a string instead of num. Vuhdo expects a num from the global function. I'm not sure if it was done this way for a purpose but I'll leave this up if any dev wants to look.

**Comment by Gogo1951** [comment]
I haven't seen this issue, I assume it's been fixed. Please re-open this if you are still getting this error. Thanks!
