### ISSUE TITLE
Set not unequipped after combat ends

### ISSUE THREAD

**Issue by Tregan** [cdmichaelb/Outfitter#71]
I've noticed that recently (probably since TBC) that if I go into combat while being mounted, the riding set is not unequipped after combat ends.

My current setup:
- Complete outfit - no automation
- Mounted accessoiry outfit - replaces trinket while riding

Am I doing something wrong, or did Blizzard just broke this awesome feature?

**Comment by Gogo1951** [comment]
Tagging this into #99
