### ISSUE TITLE
Lua Error - Moving / Clicking Minimap Button

### ISSUE THREAD

**Issue by boktai1000** [cdmichaelb/Outfitter#72]
1x ...tter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua:1421: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: LibDropdownFrame0:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Outfitter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua"]:1421: in function `Show'
[string "@Outfitter\OutfitterMinimapButton.lua"]:268: in function `ToggleMenu'
[string "*:OnMouseUp"]:1: in function <[string "*:OnMouseUp"]:1>

Locals:
(*temporary) = LibDropdownFrame0 {
 BottomLeftCorner = <unnamed> {
 }
 AcquireButton = <function> defined @Outfitter\Libraries/LibDropdown-1.0.lua:574
 released = false
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:239
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:477
 dataname = "Root menu"
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 isDropdownFrame = true
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:381
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:416
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:369
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:496
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:434
 Release = <function> defined @Outfitter\Libraries/LibDropdown-1.0.lua:547
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:353
 data = <table> {
 }
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:269
 TopRightCorner = <unnamed> {
 }
 rootMenu = true
 Center = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:275
 0 = <userdata>
 buttons = <table> {
 }
 TopEdge = <unnamed> {
 }
 Refresh = <function> defined @Outfitter\Libraries/LibDropdown-1.0.lua:230
 BottomEdge = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 GetRoot = <function> defined @Outfitter\Libraries/LibDropdown-1.0.lua:240
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:301
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:365
 AddButton = <function> defined @Outfitter\Libraries/LibDropdown-1.0.lua:215
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:333
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:486
 LeftEdge = <unnamed> {
 }
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:509
}
(*temporary) = "TOPRIGHT"
(*temporary) = OutfitterMinimapButton {
 0 = <userdata>
 SetPositionAngle = <function> defined @Outfitter\OutfitterMinimapButton.lua:90
 HideMenu = <function> defined @Outfitter\OutfitterMinimapButton.lua:212
 CurrentOutfitTexture = <unnamed> {
 }
 SetPosition = <function> defined @Outfitter\OutfitterMinimapButton.lua:82
 UpdateDragPosition = <function> defined @Outfitter\OutfitterMinimapButton.lua:40
 CursorStartX = 1751.000062
 DragStart = <function> defined @Outfitter\OutfitterMinimapButton.lua:32
 DragEnd = <function> defined @Outfitter\OutfitterMinimapButton.lua:36
 EnableFreeDrag = false
 CenterStartY = -19.471191
 ShowMenu = <function> defined @Outfitter\OutfitterMinimapButton.lua:221
 CursorStartY = 1086.000085
 dropDownMenu = <table> {
 }
 Inherit = <function> defined @Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua:149
 ToggleMenu = <function> defined @Outfitter\OutfitterMinimapButton.lua:244
 CenterStartX = -78.838623
 Construct = <function> defined @Outfitter\OutfitterMinimapButton.lua:3
 MouseDown = <function> defined @Outfitter\OutfitterMinimapButton.lua:12
}
(*temporary) = "TOPRIGHT"
(*temporary) = -20
(*temporary) = -20

**Comment by Gogo1951** [comment]
Tagging this into #84
