### ISSUE TITLE
Outfitter Not Recognizing Tree Shapeshift

### ISSUE THREAD

**Issue by downthesun01** [cdmichaelb/Outfitter#73]
I hadn't had an issue with Outfitter prior, but I recently respecced from Moonkin to Tree and Outfitter Classic doesn't recognize the shapeshift to swap gear. When shifting into Tree, casterform gets selected. All the other shapeshifts work correctly, as does Riding.

I thought that maybe this is an Outfitter issue, so I deleted it and got Itemrack, but still have the same issue.

I even went as far as to delete my WTF folder, but that still didn't resolve the issue.

Any other ideas? I'm willing to go as far as completely uninstalling, but I don't want to go to that effort, if there's an easier way to fix this

**Comment by Gogo1951** [comment]
Tagging this into #103
