### ISSUE TITLE
Swift Flight Form ''missing'' in the Druid Script section 

### ISSUE THREAD

**Issue by maanling** [cdmichaelb/Outfitter#76]
Hi! 

I was surprised to see the Swift Flight Form and the normal Flight form are not listed in the automation section with the Druid scripts. Would this be something that can be added? 

I would like to auto equip the ''Charm of Swift Flight'' trinket that increases flight speed by 10%, but without this auto script option i'm not sure how to do it. 

Thank you in advance!

**Comment by justthompson** [comment]
Same here, 
As a work around, I tried to build a manual automation script to Detect buff: Swift Flight Form, still didn't work.

**Comment by VirusViper** [comment]
+1 Please update to include Swift Flight Form.

**Comment by juntadna** [comment]
Edit: New to GitHub. Just entered a pull request for the fix.  Hopefully cdmichaelb will update it.

~~[SwiftFlightFormFix.zip]~~

~~Replace the two files in your Addon folder with these.  Will support Swift Flight Form only.~~

**Comment by justthompson** [comment]
Tested out the new Version.
Does not seem to work.
![image](https://user-images.githubusercontent.com/66805144/133910606-3b900006-3db9-403b-9b86-a6e5a635e78b.png)

Switching to SFF did not trigger automation
![image](https://user-images.githubusercontent.com/66805144/133910626-faa4ebbd-0307-4278-b9ad-25eecae245a1.png)

**Comment by VirusViper** [comment]
I made myself a workaround...

I don't use the travel form with any outfits so I edited the outfitter file and changed the spell id from travel form to swift flight form, now when I enter flight it equips items from the travel form setup which works for me.

**Comment by juntadna** [comment]
> Tested out the new Version.
> Does not seem to work.
> ![image]
> 
> Switching to SFF did not trigger automation
> ![image]

I am not able to reproduce.
The preset script "Druid: Swift Flight Form" should work for any outfit.  Is the automation script "Druid: Swift Flight Form" selected in the drop down settings for the outfit?  
Is "Disable all outfit scripts" unselected in the options menu?

**Comment by justthompson** [comment]
Yes Druid SFF was selected in the script settings
Disable all Scripts was not checked

Decided to uninstall outfitter and remove all references in the WTF folder and install fresh.
(i have been using outfitter since wow classic Launched, and have been upgrading it with each new release.)

After fresh install of the addon, It seems to work fine.

**Comment by OidaOukEidos** [comment]
It's rather hidden: On the outfit, click the down arrow on the right. Select "script settings", then check the "allow complete outfits to unequip" option.

**Comment by Gogo1951** [comment]
I play a Druid a lot... haven't seen this. Please open a new ticket if this is still an issue for anyone.
