### ISSUE TITLE
Swift Flight Form issue

### ISSUE THREAD

**Issue by Nitti2909** [cdmichaelb/Outfitter#80]
If i have more than one set selected, like my default set is my Cat set, if i then switch to my Bear set and thereby activating them both, swift flight form doesn't work it activates but doesn't change the trinket to Charm of Swift Flight .
If i do the same with mounting a mount with both set activated it works fine with Riding Crop.
So if its the trinket or the form that is the problem, i cant say...
Tried reinstalling, didn't help...
Forgot to say it works fine as long as i only have 1 set selected...

Best regards 
Nitti

**Comment by Gogo1951** [comment]
I haven't noticed this on my Druid, and that's my main. 

Hey @Nitti2909 please re-open this issue if it's still happening. Thanks!
