### ISSUE TITLE
TBC 2.5.3 Dropdown menus don't work since new patch

### ISSUE THREAD

**Issue by FranckMarcotte** [cdmichaelb/Outfitter#87]
Whenever I click the tiny arrow next to a gear set, I get this lua error :

Message: ...rface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:96: attempt to call method 'GetBackdrop' (a nil value)
Time: Tue Jan 18 22:25:07 2022
Count: 1
Stack: ...rface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:96: attempt to call method 'GetBackdrop' (a nil value)
[string "@Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua"]:96: in function <...rface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:95>
[string "@Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua"]:615: in function <...rface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:613>
[string "@Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua"]:1028: in function `OpenAce3Menu'
[string "@Interface\AddOns\Outfitter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua"]:1420: in function `Show'
[string "@Interface\AddOns\Outfitter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua"]:1557: in function `ToggleMenu'
[string "@Interface\AddOns\Outfitter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua"]:1503: in function <...tter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua:1502>

Locals: frame = LibDropdownFrame0 {
 0 = <userdata>
 AcquireButton = <function> defined @Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:574
 OnBackdropLoaded = <function> defined @Interface\SharedXML\Backdrop.lua:144
 GetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:382
 SetupTextureCoordinates = <function> defined @Interface\SharedXML\Backdrop.lua:206
 OnBackdropSizeChanged = <function> defined @Interface\SharedXML\Backdrop.lua:174
 HasBackdropInfo = <function> defined @Interface\SharedXML\Backdrop.lua:270
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:414
 isDropdownFrame = true
 GetEdgeSize = <function> defined @Interface\SharedXML\Backdrop.lua:180
 Release = <function> defined @Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:547
 ApplyBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:286
 SetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:274
 GetRoot = <function> defined @Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:240
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:339
 AddButton = <function> defined @Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:215
 SetupPieceVisuals = <function> defined @Interface\SharedXML\Backdrop.lua:238
 SetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:391
 Refresh = <function> defined @Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:230
 SetBorderBlendMode = <function> defined @Interface\SharedXML\Backdrop.lua:258
}
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 GetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:182
 SetHyperlink = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:186
 SetCraftItem = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 SetQuestRewardSpell = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 MAMover = TooltipMover {
 }
 comparing = false
 SetSocketGem = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:190
 SetPetAction = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibE

**Comment by sofar** [comment]
Confirmed broken for me as well and several others.

Interesting that the `GetBackDrop` call is at issue here - this is the same function that breaks if you want to build a gear set based on stats - something that also has been broken in BCC.

**Comment by kakistos153** [comment]
Also broken for me.

**Comment by cdmichaelb** [comment]
Reopen if you have any further issues.

Thanks to @balder89 for the code fixes.

**Comment by jawong** [comment]
The drop downs still don't work for me even with the latest update.

**Comment by cdmichaelb** [comment]
Can you post the new error?

**Comment by FranckMarcotte** [comment]
Looking like the same/similar error after update :

Message: ...rface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:97: attempt to call method 'GetBackdrop' (a nil value)
Time: Wed Jan 19 22:08:29 2022
Count: 1
Stack: ...rface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:97: attempt to call method 'GetBackdrop' (a nil value)
[string "@Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua"]:97: in function <...rface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:95>
[string "@Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua"]:616: in function <...rface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:614>
[string "@Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua"]:1029: in function `OpenAce3Menu'
[string "@Interface\AddOns\Outfitter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua"]:1420: in function `Show'
[string "@Interface\AddOns\Outfitter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua"]:1557: in function `ToggleMenu'
[string "@Interface\AddOns\Outfitter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua"]:1503: in function <...tter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua:1502>

Locals: frame = LibDropdownFrame0 {
 0 = <userdata>
 AcquireButton = <function> defined @Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:575
 OnBackdropLoaded = <function> defined @Interface\SharedXML\Backdrop.lua:144
 GetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:382
 SetupTextureCoordinates = <function> defined @Interface\SharedXML\Backdrop.lua:206
 OnBackdropSizeChanged = <function> defined @Interface\SharedXML\Backdrop.lua:174
 HasBackdropInfo = <function> defined @Interface\SharedXML\Backdrop.lua:270
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:414
 isDropdownFrame = true
 GetEdgeSize = <function> defined @Interface\SharedXML\Backdrop.lua:180
 Release = <function> defined @Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:548
 ApplyBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:286
 SetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:274
 GetRoot = <function> defined @Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:241
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:339
 AddButton = <function> defined @Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:216
 SetupPieceVisuals = <function> defined @Interface\SharedXML\Backdrop.lua:238
 SetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:391
 Refresh = <function> defined @Interface\AddOns\Outfitter\Libraries/LibDropdown-1.0.lua:231
 SetBorderBlendMode = <function> defined @Interface\SharedXML\Backdrop.lua:258
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 SetCenterColor = <function> defined @Interface\SharedXML\NineSlice.lua:224
 GetFrameLayoutTextureKit = <function> defined @Interface\SharedXML\NineSlice.lua:213
 Center = <unnamed> {
 }
 GetBorderColor = <function> defined @Interface\SharedXML\NineSlice.lua:249
 TopRightCorner = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 OnLoad = <function> defined @Interface\SharedXML\NineSlice.lua:217
 TopEdge = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 GetCenterColor = <function> defined @Interface\SharedXML\NineSlice.lua:231
 SetBorderBlendMode = <function> defined @Interface\SharedXML\NineSlice.lua:261
 GetFrameLayoutType = <function> defined @Interface\SharedXML\NineSlice.lua:209
 BottomRightCorner = <unnamed> {
 }
 SetBorderColor = <function> defined @Interface\SharedXML\NineSlice.lua:238
 LeftEdge = <unnamed> {
 }
 BottomLeftCorner = <unnamed> {
 }
}
(*temporary) = "attempt to call method 'GetBackdrop' (a nil value)"
GameTooltip = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 GetBackdropColor = <function> defined @Int

**Comment by cdmichaelb** [comment]
I thought it might be that, not sure why it worked for @balder89 , I'll do my best to fix it off memory. I don't have an active wow sub and haven't played since the launch week of tbcc.

**Comment by FranckMarcotte** [comment]
I'm down to fund your wow sub + tip if you're gonna look into it! Love your add-on <3

**Comment by MotherGinger** [comment]
I have raised a PR to address this, in the meantime you can make the same change locally if you need until a new version is released

**Comment by jawong** [comment]
Thanks for the fix @MotherGinger , the second commit appears to have broken the drop downs again for me but I applied the first commit manually and have managed to get it working again at least, UI issues notwithstanding.

**Comment by balder89** [comment]
First of all, sorry for the half (?) fix and for the late answer :/. Second, sorry for my english.

@cdmichaelb it's a very good question :/... btw it's still working for me, so I don't fully understand why it doesn't work for the others :/.

Anyway thanks for the fix @MotherGinger, I manually applied your whole fix (both commits), and it works for me.

**Comment by MotherGinger** [comment]
> Thanks for the fix @MotherGinger , the second commit appears to have broken the drop downs again for me but I applied the first commit manually and have managed to get it working again at least, UI issues notwithstanding.

I've added a couple more adjustments, I was able to replicate what you were seeing with elvui disabled, it looks like certain addons might be setting backdrops of their own that might be tripping it up (GameTooltip is a notorious globally shared object), but I can't be certain

I've added a guard to make sure it works when the tooltip doesn't seem to have a backdrop, let me know if that works out

**Comment by Mkiwoi** [comment]
https://i.imgur.com/3jEqbyp.png ingame error?

**Comment by Mkiwoi** [comment]
@MotherGinger Amazing work. I needed this. 
Also struggling with Fontain (old font replacement addon) that loads but /fontain doesn't bring up the backdrop and dropdown. Any clues?

**Comment by MotherGinger** [comment]
> @MotherGinger Amazing work. I needed this. Also struggling with Fontain (old font replacement addon) that loads but /fontain doesn't bring up the backdrop and dropdown. Any clues?

I've posted a reply on their [curseforge page](https://www.curseforge.com/wow/addons/fontain?comment=136)

**Comment by Gogo1951** [comment]
Working now though. (=
