### ISSUE TITLE
SOM - Creating new set always defaults to  Riding event

### ISSUE THREAD

**Issue by lvangh** [cdmichaelb/Outfitter#92]
Just installed for  SOM, thank you for the update. Ver 2.5.1 latest. 

I created a new set for riding, but now whenever I create a new blank set, even though not event is selected,  it automatically makes it for riding. 

![image](https://user-images.githubusercontent.com/19690096/150479839-656392df-e7f7-4855-bd56-52a391e51e7c.png)

**Comment by lvangh** [comment]
After a relog, it stopped doing this, so seems like a session bug after creating a riding set.

**Comment by Gogo1951** [comment]
If this is still an issue, feel free to re-open this ticket.
