### ISSUE TITLE
Error when clicking arrow: 1421: Action[SetPoint] failed because[SetPoint would result in anchor family connection

### ISSUE THREAD

**Issue by lvangh** [cdmichaelb/Outfitter#93]
When clicking on the down arrow with a set that has a low mana event I get this error. Latest ver, SOM. 

![image](https://user-images.githubusercontent.com/19690096/151087516-891e77b4-209e-47e3-9df6-e3bc583f342c.png)

**Comment by Gogo1951** [comment]
Hey @ivangh - Still an issue?

**Comment by lvangh** [comment]
Unable to verify unfortunately. Ty
