### ISSUE TITLE
Error when deselecting a target 1.14 SOM

### ISSUE THREAD

**Issue by lvangh** [cdmichaelb/Outfitter#94]
I have a "equip on target" test setup outfit called "Heal-AR" . I set it to Ironforge guard for the test. 

When I select it, the gear swap works, but when I hit ESC to clear target, I get this wow UI error
![image](https://user-images.githubusercontent.com/19690096/152255392-6321dd67-778b-40a5-a7e2-e6510af2a7e9.png)

**Comment by lvangh** [comment]
The equip on target code is the default
```
-- $EVENTS PLAYER_TARGET_CHANGED
-- $DESC Equips the outfit when your target changes to the specified name

-- $SETTING targetName = {type="string", label="Target name"}

-- Equip if it's the specified target
if UnitName("target"):lower() == setting.targetName:lower() then
    equip = true
end
```

**Comment by Gogo1951** [comment]
If this is still an issue, feel free to re-open this ticket.
