### ISSUE TITLE
GitHub Actions should Not Be Set to Auto-Close Issues

### ISSUE THREAD

**Issue by Gogo1951** [cdmichaelb/Outfitter#98]
Hey Guys,

Seems like you have GitHub Actions set to automatically close old issues.

Is this project just dead? Should we move away from it?

I've always loved Outfitter... but I get that it's tedious to support these add-ons. 

Any plans of continuing work on this? Closing issues that are a certain age without resolving them seems like a "Let's Just Give Up" move.

**Comment by cdmichaelb** [comment]
You're right they shouldn't. I didn't think they were. I'll fix that. It was supposed to just be "bump"ing stale issues to see if the original posters still had issues.

**Comment by cdmichaelb** [comment]
Also, I'm mostly not working on this project, I'm maintaining it. Since I don't play wow anymore, I depend on others to submit code. I am looking for another maintainer, or perhaps someone to even take it over.

**Comment by Gogo1951** [comment]
Shame but I get it.

I haven't really had the heart to work on my add-ons either.

BUT... this add-on was so much better than the shit that came after. Key-binds, Pawn-integration, like I couldn't tank without it.

I see the shit tanks struggling to switch gear around, I see the idiots with riding crops on... like... I never had to deal with any of that shit. Outfitter just worked magic for me.

Cheers mate!

**Comment by Gogo1951** [comment]
Fixed.
