### ISSUE TITLE
Ensure That the "Dismount" Event Fires when you Fly into an Instance

### ISSUE THREAD

**Issue by Gogo1951** [cdmichaelb/Outfitter#99]
Why you fly or ride into an instance, it doesn't trigger the dismount set reset. So your riding crop stays on.

I think the set reset should trigger on zone load as well as dismount.

**Comment by cdmichaelb** [comment]
I'll look into it.

**Comment by Gogo1951** [comment]
Not really relevant any more since we don't use riding crops =P
